spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: 1903